import type { UiAgit, UiAgitMember, UiAgitTopic, UiCardChatMessage } from "@/types/agit/ui";

export const AGIT_LIST: UiAgit[] = [
  {
    id: "agit-run",
    name: "러닝 메이트의 30일",
    memberCount: 4,
    maxMembers: 5,
    description: "매일의 러닝과 작은 성취를 영상으로 나누는 방이에요.",
    coverGradient: "linear-gradient(104deg, #2e1f52 0%, #7a5cfa 100%)",
    topicCount: 3,
    visibility: "public",
    category: "운동",
    ownerName: "안유진",
    todayVideoCount: 4,
    videoCount: 23,
    topicSummary: "아침 러닝 · 식단",
    thumbnailSrc: "/plip/daily-loop/room-thumbnail.png",
    joined: false,
  },
  {
    id: "agit-diet",
    name: "식단 기록방",
    memberCount: 6,
    maxMembers: 10,
    description: "하루 한 끼를 영상으로 남겨요.",
    coverGradient: "linear-gradient(135deg, #3a1f5c, #1e228a)",
    topicCount: 1,
    visibility: "public",
    category: "성장",
    ownerName: "건강한한끼",
    joined: false,
  },
  {
    id: "agit-hangang",
    name: "주말 한강 산책 모임",
    memberCount: 3,
    maxMembers: 5,
    description: "가볍게 걷고 그날의 풍경을 한 편씩 남겨요.",
    coverGradient: "linear-gradient(135deg, #3a1f5c, #1e228a)",
    topicCount: 2,
    visibility: "private",
    category: "일상",
    ownerName: "박서준",
    todayVideoCount: 0,
    topicSummary: "주말 산책 · 오늘의 풍경",
    joined: false,
  },
  {
    id: "azit-walk",
    name: "새벽 러너스",
    memberCount: 4,
    maxMembers: 5,
    description: "매일 아침 러닝을 영상으로 나눠요.",
    coverGradient: "linear-gradient(135deg, #1a4d6e 0%, #6c4bf4 100%)",
    topicCount: 6,
    visibility: "private",
    ownerName: "안지민",
    todayVideoCount: 4,
    topicSummary: "7시 러닝 인증",
    thumbnailSrc: "/plip/v13/topic-video-1.png",
    hasNewChat: true,
    hasTodayTopic: true,
    joined: true,
  },
  {
    id: "agit-gym",
    name: "영어 1분",
    memberCount: 5,
    maxMembers: 8,
    description: "하루 1분 영어 말하기.",
    coverGradient: "linear-gradient(135deg, #0f3d3a 0%, #2a8f7a 100%)",
    topicCount: 4,
    visibility: "public",
    ownerName: "하린",
    todayVideoCount: 3,
    topicSummary: "오늘의 표현",
    thumbnailSrc: "/plip/v13/topic-video-2.png",
    hasNewChat: false,
    hasTodayTopic: true,
    joined: true,
  },
  {
    id: "agit-cook",
    name: "주말 드로잉",
    memberCount: 3,
    maxMembers: 5,
    description: "주말마다 한 장의 그림을 남겨요.",
    coverGradient: "linear-gradient(135deg, #4a2f6b 0%, #c76bf4 100%)",
    topicCount: 5,
    visibility: "public",
    ownerName: "유나",
    todayVideoCount: 2,
    topicSummary: "스케치 챌린지",
    thumbnailSrc: "/plip/v13/topic-video-3.png",
    hasNewChat: true,
    hasTodayTopic: false,
    joined: true,
  },
  {
    id: "agit-study",
    name: "퇴근 후 1시간 공부",
    memberCount: 3,
    maxMembers: 5,
    description: "퇴근 후 한 시간만 집중해서 공부해요.",
    coverGradient: "linear-gradient(135deg, #2e1f52, #7a5cfa)",
    topicCount: 2,
    visibility: "public",
    category: "공부",
    thumbnailSrc: "/plip/daily-loop/explore-thumb-1.png",
    joined: false,
  },
  {
    id: "agit-dish",
    name: "하루 한 접시",
    memberCount: 5,
    maxMembers: 8,
    description: "오늘 한 끼를 접시 위로 남겨요.",
    coverGradient: "linear-gradient(135deg, #3a1f5c, #1e228a)",
    topicCount: 1,
    visibility: "public",
    category: "일상",
    thumbnailSrc: "/plip/daily-loop/explore-thumb-2.png",
    joined: false,
  },
];

export const AGIT_MEMBERS: UiAgitMember[] = [
  { id: "m1", name: "플립이", role: "owner" },
  { id: "m2", name: "클립러", role: "member" },
  { id: "m3", name: "요리왕", role: "member" },
  { id: "m4", name: "산책러", role: "member" },
];

export const AGIT_TOPICS: UiAgitTopic[] = [
  { id: "t1", title: "이번 주 하이라이트", clipCount: 12 },
  { id: "t2", title: "인증 챌린지", clipCount: 8 },
  { id: "t3", title: "자유 토픽", clipCount: 21 },
];

export const AGIT_CHAT: UiCardChatMessage[] = [
  {
    id: "c1",
    senderName: "민지",
    body: "오늘 영상 올리기 전에 태그를 먼저 정할까요?",
    isMine: false,
    time: "오후 8:40",
  },
  {
    id: "c2",
    senderName: "나",
    body: "좋아요. 후보를 세 개로 만들어봤어요!",
    isMine: true,
    time: "오후 8:42",
    replyTo: { name: "민지", excerpt: "태그를 먼저 정할까요?" },
  },
];

export function getAgitById(agitId: string): UiAgit | undefined {
  return AGIT_LIST.find((agit) => agit.id === agitId);
}
